In [1]:
import pandas as pd

In [8]:
df=pd.read_csv("../data/hour.csv")
df.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [18]:
df = pd.read_csv("../data/day.csv")
df1 = df[['instant', 'dteday', 'season', 'temp', 'hum', 'windspeed']]

In [19]:
df1.head()

   instant      dteday  season      temp       hum  windspeed
0        1  2011-01-01       1  0.344167  0.805833   0.160446
1        2  2011-01-02       1  0.363478  0.696087   0.248539
2        3  2011-01-03       1  0.196364  0.437273   0.248309
3        4  2011-01-04       1  0.200000  0.590435   0.160296
4        5  2011-01-05       1  0.226957  0.436957   0.186900

In [21]:
df1.to_csv("../data/latihan01.csv")